define(["require", "exports", "tslib", "@arcgis/core/symbols/CIMSymbol"], function (require, exports, tslib_1, CIMSymbol_1) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    CIMSymbol_1 = tslib_1.__importDefault(CIMSymbol_1);
    var symbol = new CIMSymbol_1.default({
        data: {
            type: "CIMSymbolReference",
            symbol: {
                "type": "CIMPointSymbol",
                "symbolLayers": [
                    {
                        "type": "CIMVectorMarker",
                        "enable": true,
                        "anchorPointUnits": "Relative",
                        "dominantSizeAxis3D": "Y",
                        "size": 19,
                        "billboardMode3D": "FaceNearPlane",
                        "frame": {
                            "xmin": 0,
                            "ymin": 0,
                            "xmax": 24,
                            "ymax": 24
                        },
                        "markerGraphics": [
                            {
                                "type": "CIMMarkerGraphic",
                                "geometry": {
                                    "rings": [
                                        [
                                            [
                                                17.11,
                                                2.6
                                            ],
                                            [
                                                8.63,
                                                17.29
                                            ],
                                            [
                                                0.15,
                                                2.6
                                            ],
                                            [
                                                17.11,
                                                2.6
                                            ]
                                        ]
                                    ]
                                },
                                "symbol": {
                                    "type": "CIMPolygonSymbol",
                                    "symbolLayers": [
                                        {
                                            "type": "CIMSolidFill",
                                            "enable": true,
                                            "color": [
                                                255,
                                                255,
                                                255,
                                                255
                                            ]
                                        }
                                    ]
                                }
                            },
                            {
                                "type": "CIMMarkerGraphic",
                                "geometry": {
                                    "rings": [
                                        [
                                            [
                                                13.6,
                                                2.6
                                            ],
                                            [
                                                23.8,
                                                2.6
                                            ],
                                            [
                                                23.23,
                                                3.59
                                            ],
                                            [
                                                18.7,
                                                11.43
                                            ],
                                            [
                                                13.6,
                                                20.25
                                            ],
                                            [
                                                8.51,
                                                11.43
                                            ],
                                            [
                                                3.41,
                                                2.6
                                            ],
                                            [
                                                13.6,
                                                2.6
                                            ]
                                        ]
                                    ]
                                },
                                "symbol": {
                                    "type": "CIMPolygonSymbol",
                                    "symbolLayers": [
                                        {
                                            "type": "CIMSolidFill",
                                            "enable": true,
                                            "color": [
                                                255,
                                                255,
                                                255,
                                                255
                                            ]
                                        }
                                    ]
                                }
                            },
                            {
                                "type": "CIMMarkerGraphic",
                                "geometry": {
                                    "rings": [
                                        [
                                            [
                                                13.17,
                                                11.22
                                            ],
                                            [
                                                12.91,
                                                11.34
                                            ],
                                            [
                                                12.9,
                                                11.34
                                            ],
                                            [
                                                12.64,
                                                11.23
                                            ],
                                            [
                                                11.74,
                                                10.22
                                            ],
                                            [
                                                11.3,
                                                10.8
                                            ],
                                            [
                                                11.37,
                                                10.91
                                            ],
                                            [
                                                13.51,
                                                14.92
                                            ],
                                            [
                                                15.93,
                                                10.34
                                            ],
                                            [
                                                14.92,
                                                9.15
                                            ],
                                            [
                                                13.17,
                                                11.22
                                            ]
                                        ],
                                        [
                                            [
                                                10.38,
                                                7.33
                                            ],
                                            [
                                                10.36,
                                                7.35
                                            ],
                                            [
                                                8.99,
                                                8.72
                                            ],
                                            [
                                                8.73,
                                                8.82
                                            ],
                                            [
                                                8.48,
                                                8.7
                                            ],
                                            [
                                                7.78,
                                                7.92
                                            ],
                                            [
                                                7.16,
                                                8.44
                                            ],
                                            [
                                                9.06,
                                                11.99
                                            ],
                                            [
                                                11.52,
                                                7.34
                                            ],
                                            [
                                                10.93,
                                                6.8
                                            ],
                                            [
                                                10.38,
                                                7.33
                                            ]
                                        ],
                                        [
                                            [
                                                10.73,
                                                9.72
                                            ],
                                            [
                                                11.09,
                                                10.39
                                            ],
                                            [
                                                11.46,
                                                9.9
                                            ],
                                            [
                                                11.73,
                                                9.76
                                            ],
                                            [
                                                12,
                                                9.88
                                            ],
                                            [
                                                12.9,
                                                10.89
                                            ],
                                            [
                                                14.66,
                                                8.82
                                            ],
                                            [
                                                14.92,
                                                8.69
                                            ],
                                            [
                                                15.18,
                                                8.81
                                            ],
                                            [
                                                15.18,
                                                8.82
                                            ],
                                            [
                                                16.14,
                                                9.94
                                            ],
                                            [
                                                17.11,
                                                8.11
                                            ],
                                            [
                                                17.12,
                                                8.09
                                            ],
                                            [
                                                18.69,
                                                5.12
                                            ],
                                            [
                                                13.14,
                                                5.12
                                            ],
                                            [
                                                10.73,
                                                9.72
                                            ]
                                        ],
                                        [
                                            [
                                                6.96,
                                                8.06
                                            ],
                                            [
                                                7.57,
                                                7.56
                                            ],
                                            [
                                                7.79,
                                                7.47
                                            ],
                                            [
                                                8.05,
                                                7.59
                                            ],
                                            [
                                                8.75,
                                                8.37
                                            ],
                                            [
                                                10.08,
                                                7.03
                                            ],
                                            [
                                                10.11,
                                                7.02
                                            ],
                                            [
                                                10.68,
                                                6.46
                                            ],
                                            [
                                                10.92,
                                                6.35
                                            ],
                                            [
                                                11.16,
                                                6.45
                                            ],
                                            [
                                                11.72,
                                                6.96
                                            ],
                                            [
                                                12.69,
                                                5.12
                                            ],
                                            [
                                                5.38,
                                                5.12
                                            ],
                                            [
                                                6.96,
                                                8.06
                                            ]
                                        ],
                                        [
                                            [
                                                18.8,
                                                4.71
                                            ],
                                            [
                                                19.1,
                                                4.87
                                            ],
                                            [
                                                19.11,
                                                5.22
                                            ],
                                            [
                                                17.49,
                                                8.28
                                            ],
                                            [
                                                17.49,
                                                8.29
                                            ],
                                            [
                                                17.47,
                                                8.31
                                            ],
                                            [
                                                13.82,
                                                15.22
                                            ],
                                            [
                                                13.51,
                                                15.41
                                            ],
                                            [
                                                13.21,
                                                15.23
                                            ],
                                            [
                                                11.02,
                                                11.15
                                            ],
                                            [
                                                10.87,
                                                10.87
                                            ],
                                            [
                                                10.49,
                                                10.17
                                            ],
                                            [
                                                9.37,
                                                12.3
                                            ],
                                            [
                                                9.16,
                                                12.47
                                            ],
                                            [
                                                9.06,
                                                12.48
                                            ],
                                            [
                                                9.05,
                                                12.48
                                            ],
                                            [
                                                9.04,
                                                12.48
                                            ],
                                            [
                                                9.03,
                                                12.48
                                            ],
                                            [
                                                9.02,
                                                12.48
                                            ],
                                            [
                                                9,
                                                12.48
                                            ],
                                            [
                                                8.99,
                                                12.47
                                            ],
                                            [
                                                8.76,
                                                12.3
                                            ],
                                            [
                                                8,
                                                10.88
                                            ],
                                            [
                                                6.71,
                                                8.48
                                            ],
                                            [
                                                4.96,
                                                5.22
                                            ],
                                            [
                                                4.97,
                                                4.87
                                            ],
                                            [
                                                5.27,
                                                4.71
                                            ],
                                            [
                                                18.8,
                                                4.71
                                            ]
                                        ]
                                    ]
                                },
                                "symbol": {
                                    "type": "CIMPolygonSymbol",
                                    "symbolLayers": [
                                        {
                                            "type": "CIMSolidFill",
                                            "enable": true,
                                            "color": [
                                                255,
                                                255,
                                                255,
                                                255
                                            ]
                                        }
                                    ]
                                }
                            },
                            {
                                "type": "CIMMarkerGraphic",
                                "geometry": {
                                    "rings": [
                                        [
                                            [
                                                15.93,
                                                10.34
                                            ],
                                            [
                                                13.51,
                                                14.92
                                            ],
                                            [
                                                11.37,
                                                10.91
                                            ],
                                            [
                                                11.3,
                                                10.8
                                            ],
                                            [
                                                11.74,
                                                10.22
                                            ],
                                            [
                                                12.64,
                                                11.23
                                            ],
                                            [
                                                12.9,
                                                11.34
                                            ],
                                            [
                                                12.91,
                                                11.34
                                            ],
                                            [
                                                13.17,
                                                11.22
                                            ],
                                            [
                                                14.92,
                                                9.15
                                            ],
                                            [
                                                15.93,
                                                10.34
                                            ]
                                        ]
                                    ]
                                },
                                "symbol": {
                                    "type": "CIMPolygonSymbol",
                                    "symbolLayers": [
                                        {
                                            "type": "CIMSolidFill",
                                            "enable": true,
                                            "color": [
                                                255,
                                                255,
                                                255,
                                                255
                                            ]
                                        }
                                    ]
                                }
                            },
                            {
                                "type": "CIMMarkerGraphic",
                                "geometry": {
                                    "rings": [
                                        [
                                            [
                                                11.52,
                                                7.34
                                            ],
                                            [
                                                9.06,
                                                11.99
                                            ],
                                            [
                                                7.16,
                                                8.44
                                            ],
                                            [
                                                7.78,
                                                7.92
                                            ],
                                            [
                                                8.48,
                                                8.7
                                            ],
                                            [
                                                8.73,
                                                8.82
                                            ],
                                            [
                                                8.99,
                                                8.72
                                            ],
                                            [
                                                10.36,
                                                7.35
                                            ],
                                            [
                                                10.38,
                                                7.33
                                            ],
                                            [
                                                10.93,
                                                6.8
                                            ],
                                            [
                                                11.52,
                                                7.34
                                            ]
                                        ]
                                    ]
                                },
                                "symbol": {
                                    "type": "CIMPolygonSymbol",
                                    "symbolLayers": [
                                        {
                                            "type": "CIMSolidFill",
                                            "enable": true,
                                            "color": [
                                                255,
                                                255,
                                                255,
                                                255
                                            ]
                                        }
                                    ]
                                }
                            },
                            {
                                "type": "CIMMarkerGraphic",
                                "geometry": {
                                    "rings": [
                                        [
                                            [
                                                18.69,
                                                5.12
                                            ],
                                            [
                                                17.12,
                                                8.09
                                            ],
                                            [
                                                17.11,
                                                8.11
                                            ],
                                            [
                                                16.14,
                                                9.94
                                            ],
                                            [
                                                15.18,
                                                8.82
                                            ],
                                            [
                                                15.18,
                                                8.81
                                            ],
                                            [
                                                14.92,
                                                8.69
                                            ],
                                            [
                                                14.66,
                                                8.82
                                            ],
                                            [
                                                12.9,
                                                10.89
                                            ],
                                            [
                                                12,
                                                9.88
                                            ],
                                            [
                                                11.73,
                                                9.76
                                            ],
                                            [
                                                11.46,
                                                9.9
                                            ],
                                            [
                                                11.09,
                                                10.39
                                            ],
                                            [
                                                10.73,
                                                9.72
                                            ],
                                            [
                                                13.14,
                                                5.12
                                            ],
                                            [
                                                18.69,
                                                5.12
                                            ]
                                        ]
                                    ]
                                },
                                "symbol": {
                                    "type": "CIMPolygonSymbol",
                                    "symbolLayers": [
                                        {
                                            "type": "CIMSolidFill",
                                            "enable": true,
                                            "color": [
                                                102,
                                                47,
                                                24,
                                                255
                                            ]
                                        }
                                    ]
                                }
                            },
                            {
                                "type": "CIMMarkerGraphic",
                                "geometry": {
                                    "rings": [
                                        [
                                            [
                                                12.69,
                                                5.12
                                            ],
                                            [
                                                11.72,
                                                6.96
                                            ],
                                            [
                                                11.16,
                                                6.45
                                            ],
                                            [
                                                10.92,
                                                6.35
                                            ],
                                            [
                                                10.68,
                                                6.46
                                            ],
                                            [
                                                10.11,
                                                7.02
                                            ],
                                            [
                                                10.08,
                                                7.03
                                            ],
                                            [
                                                8.75,
                                                8.37
                                            ],
                                            [
                                                8.05,
                                                7.59
                                            ],
                                            [
                                                7.79,
                                                7.47
                                            ],
                                            [
                                                7.57,
                                                7.55
                                            ],
                                            [
                                                6.96,
                                                8.06
                                            ],
                                            [
                                                5.38,
                                                5.12
                                            ],
                                            [
                                                12.69,
                                                5.12
                                            ]
                                        ]
                                    ]
                                },
                                "symbol": {
                                    "type": "CIMPolygonSymbol",
                                    "symbolLayers": [
                                        {
                                            "type": "CIMSolidFill",
                                            "enable": true,
                                            "color": [
                                                158,
                                                102,
                                                62,
                                                255
                                            ]
                                        }
                                    ]
                                }
                            },
                            {
                                "type": "CIMMarkerGraphic",
                                "geometry": {
                                    "rings": [
                                        [
                                            [
                                                13.17,
                                                11.22
                                            ],
                                            [
                                                12.91,
                                                11.34
                                            ],
                                            [
                                                12.9,
                                                11.34
                                            ],
                                            [
                                                12.64,
                                                11.23
                                            ],
                                            [
                                                11.74,
                                                10.22
                                            ],
                                            [
                                                11.3,
                                                10.8
                                            ],
                                            [
                                                11.37,
                                                10.91
                                            ],
                                            [
                                                13.51,
                                                14.92
                                            ],
                                            [
                                                15.93,
                                                10.34
                                            ],
                                            [
                                                14.92,
                                                9.15
                                            ],
                                            [
                                                13.17,
                                                11.22
                                            ]
                                        ],
                                        [
                                            [
                                                10.38,
                                                7.33
                                            ],
                                            [
                                                10.36,
                                                7.35
                                            ],
                                            [
                                                8.99,
                                                8.72
                                            ],
                                            [
                                                8.73,
                                                8.82
                                            ],
                                            [
                                                8.48,
                                                8.7
                                            ],
                                            [
                                                7.78,
                                                7.92
                                            ],
                                            [
                                                7.16,
                                                8.44
                                            ],
                                            [
                                                9.06,
                                                11.99
                                            ],
                                            [
                                                11.52,
                                                7.34
                                            ],
                                            [
                                                10.93,
                                                6.8
                                            ],
                                            [
                                                10.38,
                                                7.33
                                            ]
                                        ],
                                        [
                                            [
                                                6.96,
                                                8.06
                                            ],
                                            [
                                                7.57,
                                                7.55
                                            ],
                                            [
                                                7.79,
                                                7.47
                                            ],
                                            [
                                                8.05,
                                                7.59
                                            ],
                                            [
                                                8.75,
                                                8.37
                                            ],
                                            [
                                                10.08,
                                                7.03
                                            ],
                                            [
                                                10.11,
                                                7.02
                                            ],
                                            [
                                                10.68,
                                                6.46
                                            ],
                                            [
                                                10.92,
                                                6.35
                                            ],
                                            [
                                                11.16,
                                                6.45
                                            ],
                                            [
                                                11.72,
                                                6.96
                                            ],
                                            [
                                                12.69,
                                                5.12
                                            ],
                                            [
                                                5.38,
                                                5.12
                                            ],
                                            [
                                                6.96,
                                                8.06
                                            ]
                                        ],
                                        [
                                            [
                                                10.73,
                                                9.72
                                            ],
                                            [
                                                11.09,
                                                10.39
                                            ],
                                            [
                                                11.46,
                                                9.9
                                            ],
                                            [
                                                11.73,
                                                9.76
                                            ],
                                            [
                                                12,
                                                9.88
                                            ],
                                            [
                                                12.9,
                                                10.89
                                            ],
                                            [
                                                14.66,
                                                8.82
                                            ],
                                            [
                                                14.92,
                                                8.69
                                            ],
                                            [
                                                15.18,
                                                8.81
                                            ],
                                            [
                                                15.18,
                                                8.82
                                            ],
                                            [
                                                16.14,
                                                9.94
                                            ],
                                            [
                                                17.11,
                                                8.11
                                            ],
                                            [
                                                17.12,
                                                8.09
                                            ],
                                            [
                                                18.69,
                                                5.12
                                            ],
                                            [
                                                13.14,
                                                5.12
                                            ],
                                            [
                                                10.73,
                                                9.72
                                            ]
                                        ],
                                        [
                                            [
                                                18.8,
                                                4.71
                                            ],
                                            [
                                                19.1,
                                                4.87
                                            ],
                                            [
                                                19.11,
                                                5.22
                                            ],
                                            [
                                                17.49,
                                                8.28
                                            ],
                                            [
                                                17.49,
                                                8.29
                                            ],
                                            [
                                                17.47,
                                                8.31
                                            ],
                                            [
                                                13.82,
                                                15.22
                                            ],
                                            [
                                                13.51,
                                                15.41
                                            ],
                                            [
                                                13.21,
                                                15.23
                                            ],
                                            [
                                                11.02,
                                                11.15
                                            ],
                                            [
                                                10.87,
                                                10.87
                                            ],
                                            [
                                                10.5,
                                                10.17
                                            ],
                                            [
                                                9.37,
                                                12.3
                                            ],
                                            [
                                                9.16,
                                                12.47
                                            ],
                                            [
                                                9.06,
                                                12.48
                                            ],
                                            [
                                                9.05,
                                                12.48
                                            ],
                                            [
                                                9.04,
                                                12.48
                                            ],
                                            [
                                                9.03,
                                                12.48
                                            ],
                                            [
                                                9.02,
                                                12.48
                                            ],
                                            [
                                                9,
                                                12.48
                                            ],
                                            [
                                                8.99,
                                                12.47
                                            ],
                                            [
                                                8.76,
                                                12.3
                                            ],
                                            [
                                                8,
                                                10.88
                                            ],
                                            [
                                                6.71,
                                                8.49
                                            ],
                                            [
                                                6.71,
                                                8.48
                                            ],
                                            [
                                                4.96,
                                                5.22
                                            ],
                                            [
                                                4.97,
                                                4.87
                                            ],
                                            [
                                                5.27,
                                                4.71
                                            ],
                                            [
                                                18.8,
                                                4.71
                                            ]
                                        ]
                                    ]
                                },
                                "symbol": {
                                    "type": "CIMPolygonSymbol",
                                    "symbolLayers": [
                                        {
                                            "type": "CIMSolidFill",
                                            "enable": true,
                                            "color": [
                                                0,
                                                0,
                                                0,
                                                255
                                            ]
                                        }
                                    ]
                                }
                            }
                        ],
                        "scaleSymbolsProportionally": true,
                        "respectFrame": true,
                        "clippingPath": {
                            "type": "CIMClippingPath",
                            "clippingType": "Intersect",
                            "path": {
                                "rings": [
                                    [
                                        [
                                            0,
                                            0
                                        ],
                                        [
                                            24,
                                            0
                                        ],
                                        [
                                            24,
                                            24
                                        ],
                                        [
                                            0,
                                            24
                                        ],
                                        [
                                            0,
                                            0
                                        ]
                                    ]
                                ]
                            }
                        }
                    }
                ]
            }
        }
    });
    exports.default = symbol;
});
//# sourceMappingURL=MountainPassSymbol.js.map