
// import IconInfo from "../types/IconInfo"
// import { layerListIcons } from "../symbols/IconDefinitions"
import CIMSymbol from "@arcgis/core/symbols/CIMSymbol"

const weatherStationSymbol = new CIMSymbol({
  data: {
    type: "CIMSymbolReference",
    symbol: {
      "type": "CIMPointSymbol",
      "symbolLayers": [
        {
          "type": "CIMVectorMarker",
          "enable": true,
          
          "size": 24,
          "offsetY":12,
          
          "frame": {
            "xmin": 0,
            "ymin": 0,
            "xmax": 18,
            "ymax": 24
          },
          "markerGraphics": [
            {
              "type": "CIMMarkerGraphic",
                  textString:'',
                  primitiveName:'',
              "geometry": {
                "rings": [
                  [
                    [
                      15.37,
                      8.43
                    ],
                    [
                      16.49,
                      9.81
                    ],
                    [
                      17.32,
                      11.38
                    ],
                    [
                      17.83,
                      13.09
                    ],
                    [
                      18,
                      14.87
                    ],
                    [
                      17.83,
                      16.65
                    ],
                    [
                      17.32,
                      18.36
                    ],
                    [
                      16.49,
                      19.94
                    ],
                    [
                      15.36,
                      21.33
                    ],
                    [
                      14,
                      22.46
                    ],
                    [
                      12.44,
                      23.31
                    ],
                    [
                      10.76,
                      23.83
                    ],
                    [
                      9,
                      24
                    ],
                    [
                      7.24,
                      23.83
                    ],
                    [
                      5.56,
                      23.31
                    ],
                    [
                      4,
                      22.46
                    ],
                    [
                      2.64,
                      21.33
                    ],
                    [
                      1.51,
                      19.94
                    ],
                    [
                      0.68,
                      18.36
                    ],
                    [
                      0.17,
                      16.65
                    ],
                    [
                      0,
                      14.87
                    ],
                    [
                      0.17,
                      13.09
                    ],
                    [
                      0.68,
                      11.39
                    ],
                    [
                      1.5,
                      9.81
                    ],
                    [
                      2.62,
                      8.43
                    ],
                    [
                      8.18,
                      0.45
                    ],
                    [
                      8.54,
                      0.13
                    ],
                    [
                      9,
                      0.01
                    ],
                    [
                      9.46,
                      0.13
                    ],
                    [
                      9.82,
                      0.45
                    ],
                    [
                      15.37,
                      8.43
                    ]
                  ]
                ]
              },
              "symbol": {
                "type": "CIMPolygonSymbol",
                "symbolLayers": [
                  {
                    "type": "CIMSolidFill",
                    "enable": true,
                    "color": [
                      0,
                      81,
                      81,
                      255
                    ]
                  }
                ]
              }
            },
            {
              "type": "CIMMarkerGraphic",
                  textString:'',
                  primitiveName:'',
              "geometry": {
                "rings": [
                  [
                    [
                      9,
                      7.29
                    ],
                    [
                      10.51,
                      7.43
                    ],
                    [
                      11.96,
                      7.86
                    ],
                    [
                      13.3,
                      8.55
                    ],
                    [
                      14.48,
                      9.48
                    ],
                    [
                      15.45,
                      10.62
                    ],
                    [
                      16.16,
                      11.91
                    ],
                    [
                      16.6,
                      13.32
                    ],
                    [
                      16.75,
                      14.78
                    ],
                    [
                      16.6,
                      16.24
                    ],
                    [
                      16.16,
                      17.65
                    ],
                    [
                      15.45,
                      18.94
                    ],
                    [
                      14.48,
                      20.08
                    ],
                    [
                      13.3,
                      21.01
                    ],
                    [
                      11.96,
                      21.7
                    ],
                    [
                      10.51,
                      22.13
                    ],
                    [
                      9,
                      22.27
                    ],
                    [
                      7.49,
                      22.13
                    ],
                    [
                      6.04,
                      21.7
                    ],
                    [
                      4.7,
                      21.01
                    ],
                    [
                      3.52,
                      20.08
                    ],
                    [
                      2.55,
                      18.94
                    ],
                    [
                      1.84,
                      17.65
                    ],
                    [
                      1.4,
                      16.24
                    ],
                    [
                      1.25,
                      14.78
                    ],
                    [
                      1.4,
                      13.32
                    ],
                    [
                      1.84,
                      11.91
                    ],
                    [
                      2.55,
                      10.62
                    ],
                    [
                      3.52,
                      9.48
                    ],
                    [
                      4.7,
                      8.55
                    ],
                    [
                      6.04,
                      7.86
                    ],
                    [
                      7.49,
                      7.43
                    ],
                    [
                      9,
                      7.29
                    ]
                  ]
                ]
              },
              "symbol": {
                "type": "CIMPolygonSymbol",
                "symbolLayers": [
                  {
                    "type": "CIMSolidFill",
                    "enable": true,
                    "color": [
                      0,
                      81,
                      81,
                      255
                    ]
                  }
                ]
              }
            },
            {
              "type": "CIMMarkerGraphic",
                  textString:'',
                  primitiveName:'',
              "geometry": {
                "rings": [
                  [
                    [
                      16.75,
                      14.78
                    ],
                    [
                      16.6,
                      13.32
                    ],
                    [
                      16.16,
                      11.91
                    ],
                    [
                      15.45,
                      10.62
                    ],
                    [
                      14.48,
                      9.48
                    ],
                    [
                      13.3,
                      8.55
                    ],
                    [
                      11.96,
                      7.86
                    ],
                    [
                      10.51,
                      7.43
                    ],
                    [
                      9,
                      7.29
                    ],
                    [
                      7.49,
                      7.43
                    ],
                    [
                      6.04,
                      7.86
                    ],
                    [
                      4.7,
                      8.55
                    ],
                    [
                      3.52,
                      9.48
                    ],
                    [
                      2.55,
                      10.62
                    ],
                    [
                      1.84,
                      11.91
                    ],
                    [
                      1.4,
                      13.32
                    ],
                    [
                      1.25,
                      14.78
                    ],
                    [
                      1.4,
                      16.24
                    ],
                    [
                      1.84,
                      17.65
                    ],
                    [
                      2.55,
                      18.94
                    ],
                    [
                      3.52,
                      20.08
                    ],
                    [
                      4.7,
                      21.01
                    ],
                    [
                      6.04,
                      21.7
                    ],
                    [
                      7.49,
                      22.13
                    ],
                    [
                      9,
                      22.27
                    ],
                    [
                      10.51,
                      22.13
                    ],
                    [
                      11.96,
                      21.7
                    ],
                    [
                      13.3,
                      21.01
                    ],
                    [
                      14.48,
                      20.08
                    ],
                    [
                      15.45,
                      18.94
                    ],
                    [
                      16.16,
                      17.65
                    ],
                    [
                      16.6,
                      16.24
                    ],
                    [
                      16.75,
                      14.78
                    ]
                  ]
                ]
              },
              "symbol": {
                "type": "CIMPolygonSymbol",
                "symbolLayers": [
                  {
                    "type": "CIMSolidStroke",
                    "enable": true,
                    "capStyle": "Butt",
                    "joinStyle": "Miter",
                    "width": 0.5,
                    "color": [
                      255,
                      255,
                      255,
                      255
                    ]
                  }
                ]
              }
            },
            {
              "type": "CIMMarkerGraphic",
                  textString:'',
                  primitiveName:'',
              "geometry": {
                "rings": [
                  [
                    [
                      12.87,
                      11.44
                    ],
                    [
                      13.32,
                      11.49
                    ],
                    [
                      13.75,
                      11.65
                    ],
                    [
                      14.15,
                      11.91
                    ],
                    [
                      14.5,
                      12.25
                    ],
                    [
                      14.79,
                      12.68
                    ],
                    [
                      15,
                      13.15
                    ],
                    [
                      15.14,
                      13.67
                    ],
                    [
                      15.18,
                      14.21
                    ],
                    [
                      15.12,
                      14.85
                    ],
                    [
                      14.93,
                      15.45
                    ],
                    [
                      14.64,
                      15.98
                    ],
                    [
                      14.24,
                      16.43
                    ],
                    [
                      13.49,
                      16.88
                    ],
                    [
                      12.87,
                      16.98
                    ],
                    [
                      12.51,
                      16.93
                    ],
                    [
                      12.17,
                      17.89
                    ],
                    [
                      11.64,
                      18.71
                    ],
                    [
                      10.96,
                      19.37
                    ],
                    [
                      10.16,
                      19.8
                    ],
                    [
                      9.09,
                      20
                    ],
                    [
                      8.51,
                      19.95
                    ],
                    [
                      7.96,
                      19.78
                    ],
                    [
                      7.43,
                      19.52
                    ],
                    [
                      6.94,
                      19.15
                    ],
                    [
                      6.51,
                      18.7
                    ],
                    [
                      6.15,
                      18.17
                    ],
                    [
                      5.86,
                      17.57
                    ],
                    [
                      5.66,
                      16.93
                    ],
                    [
                      5.31,
                      16.98
                    ],
                    [
                      4.86,
                      16.93
                    ],
                    [
                      4.43,
                      16.77
                    ],
                    [
                      4.03,
                      16.51
                    ],
                    [
                      3.68,
                      16.17
                    ],
                    [
                      3.39,
                      15.75
                    ],
                    [
                      3.18,
                      15.27
                    ],
                    [
                      3.04,
                      14.75
                    ],
                    [
                      3,
                      14.21
                    ],
                    [
                      3.04,
                      13.67
                    ],
                    [
                      3.18,
                      13.15
                    ],
                    [
                      3.39,
                      12.68
                    ],
                    [
                      3.68,
                      12.25
                    ],
                    [
                      4.03,
                      11.91
                    ],
                    [
                      4.43,
                      11.65
                    ],
                    [
                      4.86,
                      11.49
                    ],
                    [
                      5.31,
                      11.44
                    ],
                    [
                      12.87,
                      11.44
                    ]
                  ]
                ]
              },
              "symbol": {
                "type": "CIMPolygonSymbol",
                "symbolLayers": [
                  {
                    "type": "CIMSolidFill",
                    "enable": true,
                    "color": [
                      255,
                      255,
                      255,
                      255
                    ]
                  }
                ]
              }
            },
            {
              "type": "CIMMarkerGraphic",
                  textString:'',
                  primitiveName:'',
              "geometry": {
                "rings": [
                  [
                    [
                      9.44,
                      14.8
                    ],
                    [
                      9.44,
                      17.51
                    ],
                    [
                      9.11,
                      17.84
                    ],
                    [
                      8.78,
                      17.51
                    ],
                    [
                      8.78,
                      14.8
                    ],
                    [
                      9.11,
                      14.47
                    ],
                    [
                      9.44,
                      14.8
                    ]
                  ]
                ]
              },
              "symbol": {
                "type": "CIMPolygonSymbol",
                "symbolLayers": [
                  {
                    "type": "CIMSolidFill",
                    "enable": true,
                    "color": [
                      0,
                      81,
                      81,
                      255
                    ]
                  }
                ]
              }
            },
            {
              "type": "CIMMarkerGraphic",
                  textString:'',
                  primitiveName:'',
              "geometry": {
                "rings": [
                  [
                    [
                      9.374,
                      12.868
                    ],
                    [
                      9.533,
                      13.084
                    ],
                    [
                      9.558,
                      13.363
                    ],
                    [
                      9.44,
                      13.609
                    ],
                    [
                      9.219,
                      13.741
                    ],
                    [
                      8.969,
                      13.713
                    ],
                    [
                      8.776,
                      13.536
                    ],
                    [
                      8.703,
                      13.269
                    ],
                    [
                      8.83,
                      12.928
                    ],
                    [
                      9.135,
                      12.787
                    ],
                    [
                      9.374,
                      12.868
                    ]
                  ]
                ]
              },
              "symbol": {
                "type": "CIMPolygonSymbol",
                "symbolLayers": [
                  {
                    "type": "CIMSolidFill",
                    "enable": true,
                    "color": [
                      0,
                      81,
                      81,
                      255
                    ]
                  }
                ]
              }
            }
          ],
          "scaleSymbolsProportionally": true,
          "respectFrame": true,
        }
      ]
    }
  }
})
export default weatherStationSymbol