# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
# - develop
- none

pool: Default

stages:
- stage: Build
  displayName: "Build the application"
  jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      name: InstallNode
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - script: |
        npm ci
      name: npmci
      displayName: 'Install dependencies'

        
    - script: |
        npm run build
      name: build
      displayName: 'Run the npm build script using $(Build.SourcesDirectory)'
      workingDirectory: $(Build.SourcesDirectory)

- stage: PublishArtifacts
  displayName: "Publish Artifacts"
  dependsOn: Build
  jobs:
  - job: PublishArtifacts
    displayName: "Publish Artifacts"
    steps:
    - task: CopyFiles@2
      name: CopyFilesToArtifactStagingDirectory
      displayName: 'Copy Files to artifact staging directory: "$(Build.ArtifactStagingDirectory)"'
      inputs:
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        Contents: 'dist/**'

    - task: PublishBuildArtifacts@1
      name: PublishArtifacts
      displayName: "Publish Artifacts"
      inputs: 
        PathtoPublish: $(Build.ArtifactStagingDirectory) # dist files
        ArtifactName: 'www' # output artifact named www
